### ISSUE TITLE
Record could not get accessed

### ISSUE THREAD

**Issue by dongli** [AER-RC/AER_Line_File#1] opened 2021-07-21 09:04 UTC
I changed to use python3 to run get_line_file.py, but encounter the following print:
```
$ ./get_line_file.py
Record could not get accessed.
```

**Comment by pernak18** [comment] 2021-07-21 13:02
hi @dongli . i cannot reproduce this error. please try a [direct download](https://zenodo.org/record/4019178/files/aer_v_3.8.1.tar.gz?download=1) of the line file and let us know if that works. note that we have upgraded from v3.8 to 3.8.1

**Comment by georgehaan** [comment] 2021-10-19 06:04
I just run ./get_line_file.py to get 3.8.1.tar.gz, but in vain:

$ ./get_line_file.py
Title: AER Line File Parameters
Keywords: Spectroscopy, AER, HITRAN, Atmospheric Modeling, Radiative Transfer
Publication date: 2020-05-21
DOI: 10.5281/zenodo.4019086
Total size: 422.3 MB

Link: https://zenodo.org/api/files/8b30d5f8-6508-499b-b068-6ff669d46e4f/aer_v_3.
8.tar.gz   size: 422.3 MB
100% [..................................................] 442810401 / 442810401
Checksum is correct. (fb8ac2a772602a529975264d170fd21b)

Link: https://zenodo.org/api/files/8b30d5f8-6508-499b-b068-6ff669d46e4f/LICENSE
  size: 0.0 MB
100% [..............................................................] 665 / 665
Checksum is correct. (4130fd97024cac14930391afcc9f4c75)
All files have been downloaded.

**Comment by pernak18** [comment] 2022-08-04 12:39
@dongli closing for now, but feel free to reopen if what i suggested still didn't work

please and thanks,

**Closed as completed by pernak18** 2022-08-04 12:39 UTC
